services:
  webhookx-migration:
    image: "webhookx-io/webhookx:latest"
    container_name: webhookx-migration
    environment:
      WEBHOOKX_DATABASE_HOST: webhookx-database
    command: webhookx migrations up
    depends_on:
      webhookx-database:
        condition: service_healthy

  webhookx:
    image: "webhookx-io/webhookx:latest"
    container_name: webhookx
    environment:
      WEBHOOKX_DATABASE_HOST: webhookx-database
      WEBHOOKX_REDIS_HOST: redis
      WEBHOOKX_SERVER_HOST: 0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      webhookx-database:
        condition: service_healthy
      redis:
        condition: service_started
      webhookx-migration:
        condition: service_started

  webhookx-database:
    image: postgres:13
    environment:
      POSTGRES_DB: webhookx
      POSTGRES_USER: webhookx
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6
