name: Test

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: build
      run: go build -v ./...

    - name: run tests
      run: go test -v ./...

  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name:
        run: |
          docker build . -t webhookx-io/webhookx:latest
          docker compose up -d
          sleep 10
          curl http://localhost:8080
